version: "3.0"

services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app

    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin